import sys
import os
from io import BytesIO

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

import streamlit as st
from fpdf import FPDF

from src.analyzer.ats_scorer import ats_score
from src.analyzer.suggestions import generate_suggestions
from src.matcher.job_matcher import missing_skills, match_score
from src.parser.resume_parser import extract_text
from src.analyzer.skill_analyzer import load_skills, extract_skills
from src.analyzer.resume_checker import is_resume
from src.analyzer.resume_checker import rule_score, ml_score

# ================= PDF FUNCTION =================
class PDF(FPDF):
    def header(self):
        self.set_font("Arial", "B", 16)
        self.set_text_color(0, 102, 204)
        self.cell(0, 10, "AI Resume Analysis Report", ln=True, align="C")
        self.ln(5)

    def section_title(self, title):
        self.set_font("Arial", "B", 12)
        self.set_text_color(50, 50, 50)
        self.cell(0, 10, title, ln=True)
        self.ln(2)

    def section_body(self, items):
        self.set_font("Arial", "", 11)
        for item in items:
            self.multi_cell(0, 8, f"- {item}")
        self.ln(3)


def generate_pdf_buffer(skills, score, missing, suggestions):
    pdf = PDF()
    pdf.add_page()

    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(0, 153, 76)
    pdf.cell(0, 10, f"Overall Score: {score}%", ln=True)
    pdf.ln(5)

    pdf.section_title("Extracted Skills")
    pdf.section_body(skills if skills else ["No skills detected"])

    pdf.section_title("Missing Skills")
    pdf.section_body(missing if missing else ["No major missing skills"])

    pdf.section_title("Suggestions")
    pdf.section_body(suggestions if suggestions else ["No suggestions"])

    pdf.ln(10)
    pdf.set_font("Arial", "I", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 8, "Generated by AI Resume Analyzer")

    pdf_output = pdf.output(dest='S').encode('latin-1')
    return BytesIO(pdf_output)


# ================= UI =================
st.set_page_config(page_title="AI Resume Analyzer", layout="wide")

st.markdown("""
<style>
.main { background-color: #0e1117; }
h1 { text-align: center; }
.card {
    background-color: #1c1f26;
    padding: 20px;
    border-radius: 10px;
    margin-bottom: 15px;
}
.skill-box {
    background-color: #262730;
    padding: 8px;
    border-radius: 6px;
    margin: 4px;
    display: inline-block;
}
</style>
""", unsafe_allow_html=True)

st.markdown("<h1>📄 AI Resume Analyzer</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align:center;'>Smart Resume Evaluation using AI</p>", unsafe_allow_html=True)

uploaded_file = st.file_uploader("Upload Resume (PDF)", type=["pdf"])
job_desc = st.text_area("Paste Job Description")


# ================= MAIN =================
if uploaded_file:
    text = extract_text(uploaded_file)

    # 🔥 DEBUG SCORES
    r_score = rule_score(text)
    m_score = ml_score(text)
    final_score = (0.6 * (r_score / 100)) + (0.4 * m_score)

    st.write("Rule Score:", r_score)
    st.write("ML Score:", m_score)
    st.write("Final Score:", final_score)

    # 🔥 CHECK
    if final_score <= 0.7:
        st.error("❌ Uploaded file does not appear to be a valid resume.")
        st.stop()

    if not text or len(text.strip()) < 50:
        st.error("❌ Resume content is too small or unreadable.")
        st.stop()

    # 🔥 Resume validation
    if not is_resume(text):
        st.error("❌ Uploaded file does not appear to be a valid resume.")
        st.stop()

    skills_list = load_skills()
    skills = extract_skills(text, skills_list)

    col1, col2 = st.columns(2)

    # 🔹 SKILLS
    with col1:
        st.subheader("🧠 Extracted Skills")
        st.markdown('<div class="card">', unsafe_allow_html=True)

        if skills:
            for skill in skills:
                st.markdown(f'<span class="skill-box">{skill}</span>', unsafe_allow_html=True)
        else:
            st.warning("No skills detected")

        st.markdown('</div>', unsafe_allow_html=True)

    # 🔹 JOB MATCH
    if job_desc and len(job_desc.strip()) > 20:

        score = match_score(text, job_desc)
        missing = missing_skills(skills, job_desc, skills_list)
        ats = ats_score(text, skills, job_desc)
        suggestions = generate_suggestions(missing, ats["Total Score"])

        # 🔹 SCORE
        with col2:
            st.markdown('<div class="card">', unsafe_allow_html=True)

            colA, colB, colC = st.columns(3)
            colA.metric("Total Score", f"{ats['Total Score']}%")
            colB.metric("Skill Score", ats["Skill Score"])
            colC.metric("Keyword Score", ats["Keyword Score"])

            st.progress(ats["Total Score"] / 100)

            st.markdown('</div>', unsafe_allow_html=True)

        # 🔹 MISSING SKILLS
        st.subheader("⚠️ Missing Skills")
        st.markdown('<div class="card">', unsafe_allow_html=True)

        if missing:
            for m in missing:
                st.markdown(f"❌ **{m}**")
        else:
            st.success("No major missing skills 🎉")

        st.markdown('</div>', unsafe_allow_html=True)

        # 🔹 SUGGESTIONS
        st.subheader("💡 Suggestions")
        st.markdown('<div class="card">', unsafe_allow_html=True)

        for s in suggestions:
            st.markdown(f"✅ {s}")

        st.markdown('</div>', unsafe_allow_html=True)

        # 🔹 PDF DOWNLOAD
        st.markdown("<br>", unsafe_allow_html=True)

        col_center = st.columns([1,2,1])[1]

        with col_center:
            if st.button("📄 Generate Report"):
                pdf_buffer = generate_pdf_buffer(
                    skills,
                    ats["Total Score"],
                    missing,
                    suggestions
                )

                st.download_button(
                    "⬇️ Download Report",
                    pdf_buffer,
                    file_name="resume_report.pdf",
                    mime="application/pdf"
                )

    else:
        st.info("👉 Please paste a valid job description to see analysis.")